### ISSUE TITLE
How about Swift 2.0 new error handling?

### ISSUE THREAD

**Issue by nevercry** [m2mtech/smashtag-2015#1]
TwitterRequest.swift  show some error  in Xcode 7.0, I have no idea how to fix that.

**Comment by nevercry** [comment]
I found solution.  

```
 do {
    propertyListResponse = try NSJSONSerialization.JSONObjectWithData(jsonResponse, options:NSJSONReadingOptions.MutableLeaves )
 }  catch  {
    let error = "Couldn't parse JSON response."
    self.log(error)
    propertyListResponse = error
}
```

 [via](http://stackoverflow.com/questions/31296545/correct-handling-of-nsjsonserialization-try-catch-in-swift-2-0)

**Comment by m2mtech** [comment]
... the new course will come soon, including Swift 2.0 ...
